/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ITPGL_cppFuncs_Connector */

#ifndef _Included_com_example_ITPGL_cppFuncs_Connector
#define _Included_com_example_ITPGL_cppFuncs_Connector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ITPGL_cppFuncs_Connector
 * Method:    ConnectToBluetooth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ITPGL_cppFuncs_Connector_ConnectToBluetooth
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
